### ISSUE TITLE
Review different PHP generators

### ISSUE THREAD

**Issue by phil-davis** [owncloud/libre-graph-api-php#3]
There are a few different PHP generators available. For example "dt", "symfony".

Quickly review those to see if any are of benefit to us for the ocis PHP SDK, or if we should just use the default "PHP" generator.

Make comments in this issue about what has been discovered. That will give us a record of the investigation and decision.

**Comment by individual-it** [comment]
# php
- bug in the templates trying to `preg_match` with a `DateTime` object, can be solved by own template or waiting for https://github.com/OpenAPITools/openapi-generator/pull/16513

# symfony
- would require the SDK to be a full symfony application

# php-dt
- made for https://github.com/Articus/DataTransfer ("This library provides a "validating hydrator", a service that patches destination data with source data only if destination data remains valid after that."). Do we need that?

**Comment by individual-it** [comment]
currently we are using `php-nextgen` see https://github.com/owncloud/libre-graph-api/pull/133
I think we can close this issue, please feel free to reopen if there are still topics to discuss
